/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myclassroommanager.presentation;

import javax.swing.JOptionPane;
import myclassroommanager.service.*;
import myclassroommanager.domain.*;

/**
 *
 * @author jamesstrater-smith
 * 
 * ViewStudentProfileUI class provides UI functionality for ViewStudentProfileUI form
 */
public class ViewStudentProfileUI extends javax.swing.JFrame {
    
    public Account account = null;
    private StudentProfileTableModel model = new StudentProfileTableModel();
    private int selectedRow = -1;
    
    public void setAccount(Account account) {
        this.account = account;
        model.setStudentProfiles(account.getStudentProfiles());
    }

    /**
     * Creates new form ViewStudentProfile
     */
    public ViewStudentProfileUI() {
        initComponents();
        
        studentProfilesTbl.setModel(model);
        
        studentProfilesTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = studentProfilesTbl.rowAtPoint(evt.getPoint());
                if (row >= 0) {
                    selectedRow = row;
                    firstNameFld.setText(model.getValueAt(row, 0).toString());
                    lastNameFld.setText(model.getValueAt(row, 1).toString());
                    guardianNameFld.setText(model.getValueAt(row, 2).toString());
                    emailFld.setText(model.getValueAt(row, 3).toString());
                    phoneNumberFld.setText(model.getValueAt(row, 4).toString());
                    genderFld.setText(model.getValueAt(row, 5).toString());
                    dobFld.setText(model.getValueAt(row, 6).toString());
                    enrollmentStatusFld.setText(model.getValueAt(row, 7).toString());
                }
            }
        });
    }
    
    /**
     * This method resets selected row
     */
    private void reset() {
        selectedRow = -1;
        firstNameFld.setText("");
        lastNameFld.setText("");
        guardianNameFld.setText("");
        emailFld.setText("");
        phoneNumberFld.setText("");
        genderFld.setText("");
        dobFld.setText("");
        enrollmentStatusFld.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        firstNameFld = new javax.swing.JTextField();
        lastNameFld = new javax.swing.JTextField();
        guardianNameFld = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        phoneNumberFld = new javax.swing.JTextField();
        emailFld = new javax.swing.JTextField();
        dobFld = new javax.swing.JFormattedTextField();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        createBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        studentProfilesTbl = new javax.swing.JTable();
        enrollmentStatusFld = new javax.swing.JTextField();
        genderFld = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Student Profile");

        jLabel2.setText("First Name:");

        jLabel3.setText("Last Name:");

        jLabel4.setText("Guardian's Name:");

        jLabel5.setText("Gender:");

        jLabel6.setText("DOB");

        jLabel7.setText("Phone Number:");

        jLabel8.setText("Email address:");

        jLabel9.setText("Enrollment Status:");

        updateBtn.setText("Update Changes");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete Profile");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        createBtn.setText("Create Profile");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        studentProfilesTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "First name", "Last name", "Email", "Phone", "Gender", "Guardian name", "DOB", "Enrollment status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(studentProfilesTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(createBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(updateBtn)
                .addGap(73, 73, 73)
                .addComponent(deleteBtn)
                .addGap(65, 65, 65))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(275, 275, 275))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(guardianNameFld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(lastNameFld, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(firstNameFld)
                                    .addComponent(genderFld))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(phoneNumberFld, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(emailFld, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dobFld, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(enrollmentStatusFld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dobFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(firstNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(phoneNumberFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(guardianNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(enrollmentStatusFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn)
                    .addComponent(deleteBtn)
                    .addComponent(createBtn))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
    * This method to create new student profile when Create Profile button is clicked
    * and adds the profile to the table
    *
    * @param evt occurs when create button is clicked
    */
    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        StudentProfile studentProfile = new StudentProfile();
        studentProfile.setFirstName(firstNameFld.getText());
        studentProfile.setLastName(lastNameFld.getText());
        studentProfile.setEmailAddress(emailFld.getText());
        studentProfile.setPhoneNumber(phoneNumberFld.getText());
        studentProfile.setGender(genderFld.getText());
        studentProfile.setGuardianName(guardianNameFld.getText());
        studentProfile.setDob(dobFld.getText());
        studentProfile.setEnrollmentStatus(enrollmentStatusFld.getText());
        //studentProfile.setStudentId(studentIdFld.getText());
        
        //validate student profile being added
        boolean isValid = studentProfile.validate();
        if (!isValid) {
            JOptionPane.showMessageDialog(this,
                    "Please make sure all text fields are filled in properly and try again",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // add the profile to the account and persist it using the service
        account.add(studentProfile);
        IAccountSvc impl = AccountSvcCacheImpl.getInstance();
        account = impl.update(account);
        if (account == null) {
            JOptionPane.showMessageDialog(this,
                    "Your new profile was not saved; please try again",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        model.fireTableDataChanged();
        
        JOptionPane.showMessageDialog(this,
                "Your new profile has been saved",
                "Saved Contact", JOptionPane.INFORMATION_MESSAGE);
        firstNameFld.setText("");
        lastNameFld.setText("");
        emailFld.setText("");
        phoneNumberFld.setText("");
        genderFld.setText("");
        guardianNameFld.setText("");
        dobFld.setText("");
        enrollmentStatusFld.setText("");
    }//GEN-LAST:event_createBtnActionPerformed

    /**
     * This method updates a selected student profile in the table
     * @param evt occurs when update button is clicked
     */
    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        if (selectedRow >= 0) {
        StudentProfile studentProfile = account.getStudentProfiles().get(selectedRow);
        studentProfile.setFirstName(firstNameFld.getText());
        studentProfile.setLastName(lastNameFld.getText());
        studentProfile.setEmailAddress(emailFld.getText());
        studentProfile.setPhoneNumber(phoneNumberFld.getText());
        studentProfile.setGender(genderFld.getText());
        studentProfile.setGuardianName(guardianNameFld.getText());
        studentProfile.setDob(dobFld.getText());
        studentProfile.setEnrollmentStatus(enrollmentStatusFld.getText());
        
        boolean isValid = studentProfile.validate();
        if (!isValid) {
            JOptionPane.showMessageDialog(this,
                    "Please make sure all text fields are filled in properly and try again",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        model.fireTableDataChanged();
        reset();
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    /**
     * This method deletes a selected student profile from the table 
     * @param evt occurs when delete button is clicked
     */
    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        if (selectedRow >= 0) {
            int selectedOption = JOptionPane.showConfirmDialog(null,
                    "Delete selected row?",
                    "Yes/No",
                    JOptionPane.YES_NO_OPTION);
            if (selectedOption == JOptionPane.YES_OPTION) {
                account.getStudentProfiles().remove(selectedRow);
                model.fireTableDataChanged();
                reset();
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewStudentProfileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewStudentProfileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewStudentProfileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewStudentProfileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewStudentProfileUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JFormattedTextField dobFld;
    private javax.swing.JTextField emailFld;
    private javax.swing.JTextField enrollmentStatusFld;
    private javax.swing.JTextField firstNameFld;
    private javax.swing.JTextField genderFld;
    private javax.swing.JTextField guardianNameFld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lastNameFld;
    private javax.swing.JTextField phoneNumberFld;
    private javax.swing.JTable studentProfilesTbl;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
